apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ubs-ttp-staging
resources:
  - ../../../base/frontend
images:
  - name: PLACEHOLDER
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-southeast-1.amazonaws.com/ubs-ttp-frontend
    newTag: latest  # replaced by CI pipeline
